[2024-05-09T02:05:18.241+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T02:05:18.301+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T02:05:18.321+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T02:05:18.322+0000] {taskinstance.py:2303} INFO - Starting attempt 8 of 12
[2024-05-09T02:05:18.358+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-08 00:00:00+00:00
[2024-05-09T02:05:18.373+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3351) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T02:05:18.376+0000] {standard_task_runner.py:63} INFO - Started process 3353 to run task
[2024-05-09T02:05:18.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag_v1', 'choose_best_model', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpwg1oyrnz']
[2024-05-09T02:05:18.383+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask choose_best_model
[2024-05-09T02:05:18.476+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [running]> on host 2b3626ba2b72
[2024-05-09T02:05:18.659+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='satyendra' AIRFLOW_CTX_DAG_ID='my_dag_v1' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T02:05:18.667+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T02:05:18.668+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-09T02:05:18.691+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2024-05-09T02:05:18.692+0000] {branch.py:36} INFO - Branch into accurate
[2024-05-09T02:05:18.693+0000] {skipmixin.py:178} INFO - Following branch accurate
[2024-05-09T02:05:18.754+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2024-05-09T02:05:18.802+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T02:05:18.842+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=my_dag_v1, task_id=choose_best_model, execution_date=20240508T000000, start_date=20240509T020518, end_date=20240509T020518
[2024-05-09T02:05:18.877+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T02:05:18.924+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-09T02:05:18.928+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
